// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7rlEraFCGVC4_r8hynZds6P_j1KhmCZo',
    appId: '1:707732582085:android:7aca24ccd88d8b01f8caac',
    messagingSenderId: '707732582085',
    projectId: 'chat-app-2d1f8',
    storageBucket: 'chat-app-2d1f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqZFfGkarX133JcAJDIGHkcNKkr2QW2Y4',
    appId: '1:707732582085:ios:6e682751fed8be76f8caac',
    messagingSenderId: '707732582085',
    projectId: 'chat-app-2d1f8',
    storageBucket: 'chat-app-2d1f8.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEl4Gz5axkNCEHp0wXGKZXwjLwidjOWRU',
    appId: '1:707732582085:web:36dd7e0fce7ec945f8caac',
    messagingSenderId: '707732582085',
    projectId: 'chat-app-2d1f8',
    authDomain: 'chat-app-2d1f8.firebaseapp.com',
    storageBucket: 'chat-app-2d1f8.appspot.com',
    measurementId: 'G-J52SGWSF5V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqZFfGkarX133JcAJDIGHkcNKkr2QW2Y4',
    appId: '1:707732582085:ios:6e682751fed8be76f8caac',
    messagingSenderId: '707732582085',
    projectId: 'chat-app-2d1f8',
    storageBucket: 'chat-app-2d1f8.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

}